spring:
  application:
    name: spring-cloud-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-ribbon:
      path: /api/ribbon/**
#      url: forward:http://localhost:8765
      serviceId: spring-cloud-web-admin-ribbon
    api-feign:
      path: /api/feign/**
#      url: forward:http://localhost:8766
      serviceId: spring-cloud-web-admin-feign
  strip-prefix: false